blank_issues_enabled: false
contact_links:
#  - name: Support Forums
#    url: https://forums.pcsx2.net/index.php
#    about: For community support and answers
  - name: Discord
    url: https://discord.gg/ghpjzNX7pH
    about: Get direct support and hang out with us
  - name: Wiki
    url: https://ps2homebrew-arcade.github.io/pcsx2x6/
    about: For user provided information and reports
